begin;

create table if not exists categories (
  category_id bigint generated by default as identity primary key,
  category_name text not null,
  slug text not null unique,
  description text,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists products (
  product_id bigint generated by default as identity primary key,
  category_id bigint not null references categories(category_id) on delete cascade,
  product_name text not null,
  slug text not null unique,
  description text,
  base_price numeric(12,2) not null default 0,
  compare_at_price numeric(12,2),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists product_colors (
  color_id bigint generated by default as identity primary key,
  product_id bigint not null references products(product_id) on delete cascade,
  color_name text not null,
  color_code text not null,
  price_adjustment numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, color_name)
);

create table if not exists product_sizes (
  size_id bigint generated by default as identity primary key,
  product_id bigint not null references products(product_id) on delete cascade,
  size_name text not null,
  price_adjustment numeric(12,2) not null default 0,
  is_active boolean not null default true,
  unique (product_id, size_name)
);

create table if not exists product_inventory (
  inventory_id bigint generated by default as identity primary key,
  product_id bigint not null references products(product_id) on delete cascade,
  color_id bigint not null references product_colors(color_id) on delete cascade,
  size_id bigint not null references product_sizes(size_id) on delete cascade,
  stock_quantity integer not null default 0,
  sku text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, color_id, size_id)
);

create table if not exists product_images (
  image_id bigint generated by default as identity primary key,
  product_id bigint not null references products(product_id) on delete cascade,
  color_id bigint not null references product_colors(color_id) on delete cascade,
  image_url text not null,
  alt_text text,
  is_primary boolean not null default false,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists banners (
  banner_id bigint generated by default as identity primary key,
  image_url text not null,
  title text,
  description text,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists coupons (
  coupon_id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('fixed', 'percentage')),
  discount_value numeric(12,2) not null,
  min_order_value numeric(12,2) not null default 0,
  max_discount numeric(12,2),
  valid_from timestamptz not null,
  valid_to timestamptz not null,
  is_active boolean not null default true,
  usage_limit integer,
  usage_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists shipping_methods (
  method_id bigint generated by default as identity primary key,
  method_name text not null unique,
  base_fee numeric(12,2) not null default 0,
  estimated_days text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists payment_methods (
  method_id bigint generated by default as identity primary key,
  method_name text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists profiles (
  id uuid primary key,
  role text not null default 'customer' check (role in ('manager', 'customer')),
  full_name text,
  email text not null unique,
  phone_number text,
  address text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  order_id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete restrict,
  recipient_name text not null,
  recipient_email text,
  recipient_phone text not null,
  shipping_address text not null,
  notes text,
  shipping_method_id bigint not null references shipping_methods(method_id),
  payment_method_id bigint references payment_methods(method_id),
  coupon_id bigint references coupons(coupon_id),
  discount_amount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  status text not null default 'Pending' check (status in ('Pending', 'Processing', 'Shipped', 'Completed', 'Cancelled')),
  order_date timestamptz not null default now()
);

create table if not exists order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id) on delete cascade,
  inventory_id bigint not null references product_inventory(inventory_id),
  quantity integer not null check (quantity > 0),
  price_at_order numeric(12,2) not null default 0
);

create table if not exists payments (
  payment_id bigint generated by default as identity primary key,
  order_id bigint not null references orders(order_id) on delete cascade,
  method_id bigint not null references payment_methods(method_id),
  amount numeric(12,2) not null default 0,
  status text not null default 'Pending' check (status in ('Pending', 'Completed', 'Failed')),
  payment_date timestamptz not null default now(),
  transaction_id text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category_id on products(category_id);
create index if not exists idx_product_colors_product_id on product_colors(product_id);
create index if not exists idx_product_sizes_product_id on product_sizes(product_id);
create index if not exists idx_product_inventory_product_id on product_inventory(product_id);
create index if not exists idx_product_inventory_color_id on product_inventory(color_id);
create index if not exists idx_product_inventory_size_id on product_inventory(size_id);
create index if not exists idx_product_images_product_id on product_images(product_id);
create index if not exists idx_product_images_color_id on product_images(color_id);
create index if not exists idx_orders_user_id on orders(user_id);
create index if not exists idx_orders_shipping_method_id on orders(shipping_method_id);
create index if not exists idx_orders_payment_method_id on orders(payment_method_id);
create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_payments_order_id on payments(order_id);

commit;